### ISSUE TITLE
Videos section

### ISSUE THREAD

**Issue by ARMmaster17** [WULF-USA/Official-Website#6]
Videos page should have an integrated player, site author-written description.

**Comment by wulf502** [comment]
How about Crimethinc's [To Change Everything](http://www.crimethinc.com/tce)?

**Comment by ARMmaster17** [comment]
The way I was thinking it was going to work was there will be a PSQL database that holds all the links, and they get added through the website. That way we aren't pushing to this repository every time we want to change something.

**Comment by wulf502** [comment]
Oh ok, so would, say, youtube and vimeo likes work

**Comment by ARMmaster17** [comment]
We'll probably just have to stick with YouTube for now. The main thing being we have to find a way to embed a player within the site. From a UX perspective people are more likely to watch a video if they can stay on the same page.

**Comment by wulf502** [comment]
Here's that one on Youtube: https://www.youtube.com/watch?v=S0Rj4mMMSYI

**Comment by ARMmaster17** [comment]
Staging on #29
